services:
  nameserver:
    build: nameserver
    image: nameserver
    ports:
      - "8761:8761"
    networks:
      - current-network

  aplicacao:
    build: TF---Projeto-e-Arquitetura-de-Software
    image: aplicacao
    ports:
      - "8000:8000"
    networks:
      - current-network
    depends_on:
      - nameserver
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://nameserver:8761/eureka
      - spring.rabbitmq.host=rabbitmq 
      - spring.rabbitmq.port=5672 
      - spring.rabbitmq.username=engsoft2 
      - spring.rabbitmq.password=engsoft2

  gateway:
    build: gateway
    image: gateway
    ports:
      - "8765:8765"
    networks:
      - current-network
    depends_on:
      - nameserver
    environment:
      - eureka.client.serviceUrl.defaultZone=http://nameserver:8761/eureka

  asscache:
    build: asscache
    image: asscache
    ports:
      - "8100"
    networks:
      - current-network
    depends_on:
      - nameserver
      - rabbitmq
    environment:
      - eureka.client.serviceUrl.defaultZone=http://nameserver:8761/eureka
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=engsoft2 
      - spring.rabbitmq.password=engsoft2

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - current-network
    environment:
      - RABBITMQ_DEFAULT_USER=engsoft2
      - RABBITMQ_DEFAULT_PASS=engsoft2

networks:
  current-network: